/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AvailableSlot {
    'staffId': number;
    'staffName': string;
    'time': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "staffId",
            "baseName": "staff_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "staffName",
            "baseName": "staff_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvailableSlot.attributeTypeMap;
    }

    public constructor() {
    }
}
