/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AvailabilityCheckResponse {
    'availableSlots': Array<string>;
    'isAvailable': boolean;
    'message'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "availableSlots",
            "baseName": "available_slots",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isAvailable",
            "baseName": "is_available",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvailabilityCheckResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
