/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NewService } from '../models/NewService';
import { HttpFile } from '../http/http';

export class BulkServiceRequest {
    'services': Array<NewService>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<NewService>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkServiceRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
