/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Service } from '../models/Service';
import { HttpFile } from '../http/http';

export class BulkServiceResponse {
    'created': Array<Service>;
    'failed': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Array<Service>",
            "format": ""
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkServiceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
