/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CalendarUser {
    'connectedAt': Date;
    'expiresAt': Date;
    'isExpired': boolean;
    'isValid': boolean;
    'userEmail': string;
    'userId': number;
    'userName': string;
    'userRole': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectedAt",
            "baseName": "connected_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isExpired",
            "baseName": "is_expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isValid",
            "baseName": "is_valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userEmail",
            "baseName": "user_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "userName",
            "baseName": "user_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "userRole",
            "baseName": "user_role",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalendarUser.attributeTypeMap;
    }

    public constructor() {
    }
}
