/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Service } from '../models/Service';
import { HttpFile } from '../http/http';

export class CategoryWithServices {
    'color'?: string | null;
    'description'?: string | null;
    'displayOrder': number;
    'id': number;
    'name': string;
    'services': Array<Service>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayOrder",
            "baseName": "display_order",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<Service>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CategoryWithServices.attributeTypeMap;
    }

    public constructor() {
    }
}
