/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ServiceAddon } from '../models/ServiceAddon';
import { HttpFile } from '../http/http';

export class CreateBookingRequest {
    'addons'?: Array<ServiceAddon> | null;
    'bookingDate': string;
    'bookingTime': string;
    'currency': string;
    'frontendUrl'?: string | null;
    'guestEmail'?: string | null;
    'guestName'?: string | null;
    'guestPhone'?: string | null;
    'notes'?: string | null;
    'priceCents': number;
    'serviceId': number;
    'staffId': number;
    'userId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addons",
            "baseName": "addons",
            "type": "Array<ServiceAddon>",
            "format": ""
        },
        {
            "name": "bookingDate",
            "baseName": "booking_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "bookingTime",
            "baseName": "booking_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "frontendUrl",
            "baseName": "frontend_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestEmail",
            "baseName": "guest_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestName",
            "baseName": "guest_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestPhone",
            "baseName": "guest_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceCents",
            "baseName": "price_cents",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "staffId",
            "baseName": "staff_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CreateBookingRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
