/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ServiceAddon } from '../models/ServiceAddon';
import { HttpFile } from '../http/http';

export class CreateNewServiceRequest {
    'addons'?: Array<ServiceAddon> | null;
    'categoryId'?: number | null;
    'color'?: string | null;
    'currency': string;
    'description'?: string | null;
    'durationMinutes': number;
    'imageUrl'?: string | null;
    'isActive': boolean;
    'name': string;
    'priceCents': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addons",
            "baseName": "addons",
            "type": "Array<ServiceAddon>",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationMinutes",
            "baseName": "duration_minutes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceCents",
            "baseName": "price_cents",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CreateNewServiceRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
