/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserResponse } from '../models/UserResponse';
import { HttpFile } from '../http/http';

export class LoginResponse {
    'tenantId': number;
    'token': string;
    'user': UserResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoginResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
