/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BookingResponse } from '../models/BookingResponse';
import { HttpFile } from '../http/http';

export class MagicLinkResponse {
    'booking': BookingResponse;
    'magicLink': string;
    'message': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "booking",
            "baseName": "booking",
            "type": "BookingResponse",
            "format": ""
        },
        {
            "name": "magicLink",
            "baseName": "magic_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MagicLinkResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
