/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PriceRange {
    'average': number;
    'max': number;
    'min': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "average",
            "baseName": "average",
            "type": "number",
            "format": "double"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PriceRange.attributeTypeMap;
    }

    public constructor() {
    }
}
