/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tenant } from '../models/Tenant';
import { HttpFile } from '../http/http';

export class RegisterTenantResponse {
    'message': string;
    'nextSteps': Array<string>;
    'tenant': Tenant;
    'token': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextSteps",
            "baseName": "next_steps",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "tenant",
            "baseName": "tenant",
            "type": "Tenant",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegisterTenantResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
