/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PopularService } from '../models/PopularService';
import { PriceRange } from '../models/PriceRange';
import { HttpFile } from '../http/http';

export class ServiceStatsResponse {
    'activeServices': number;
    'averageDuration': number;
    'averagePriceCents': number;
    'mostPopular'?: PopularService | null;
    'priceRange': PriceRange;
    'totalServices': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activeServices",
            "baseName": "active_services",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "averageDuration",
            "baseName": "average_duration",
            "type": "number",
            "format": "double"
        },
        {
            "name": "averagePriceCents",
            "baseName": "average_price_cents",
            "type": "number",
            "format": "double"
        },
        {
            "name": "mostPopular",
            "baseName": "most_popular",
            "type": "PopularService",
            "format": ""
        },
        {
            "name": "priceRange",
            "baseName": "price_range",
            "type": "PriceRange",
            "format": ""
        },
        {
            "name": "totalServices",
            "baseName": "total_services",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ServiceStatsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
