/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateAvailability {
    'dayOfWeek'?: number | null;
    'endTime'?: string | null;
    'isRecurring'?: boolean | null;
    'specificDate'?: string | null;
    'startTime'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dayOfWeek",
            "baseName": "day_of_week",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "isRecurring",
            "baseName": "is_recurring",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "specificDate",
            "baseName": "specific_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAvailability.attributeTypeMap;
    }

    public constructor() {
    }
}
